// Code generated by protoc-gen-go.
// source: greeter.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	greeter.proto

It has these top-level messages:
	GreeterRequest
	GreeterResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GreeterRequest_Language int32

const (
	GreeterRequest_English GreeterRequest_Language = 0
	GreeterRequest_Spanish GreeterRequest_Language = 1
	GreeterRequest_French  GreeterRequest_Language = 2
)

var GreeterRequest_Language_name = map[int32]string{
	0: "English",
	1: "Spanish",
	2: "French",
}
var GreeterRequest_Language_value = map[string]int32{
	"English": 0,
	"Spanish": 1,
	"French":  2,
}

func (x GreeterRequest_Language) String() string {
	return proto.EnumName(GreeterRequest_Language_name, int32(x))
}
func (GreeterRequest_Language) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type GreeterRequest struct {
	Lang GreeterRequest_Language `protobuf:"varint,1,opt,name=lang,enum=GreeterRequest_Language" json:"lang,omitempty"`
}

func (m *GreeterRequest) Reset()                    { *m = GreeterRequest{} }
func (m *GreeterRequest) String() string            { return proto.CompactTextString(m) }
func (*GreeterRequest) ProtoMessage()               {}
func (*GreeterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GreeterRequest) GetLang() GreeterRequest_Language {
	if m != nil {
		return m.Lang
	}
	return GreeterRequest_English
}

type GreeterResponse struct {
	Greet string `protobuf:"bytes,1,opt,name=greet" json:"greet,omitempty"`
}

func (m *GreeterResponse) Reset()                    { *m = GreeterResponse{} }
func (m *GreeterResponse) String() string            { return proto.CompactTextString(m) }
func (*GreeterResponse) ProtoMessage()               {}
func (*GreeterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GreeterResponse) GetGreet() string {
	if m != nil {
		return m.Greet
	}
	return ""
}

func init() {
	proto.RegisterType((*GreeterRequest)(nil), "GreeterRequest")
	proto.RegisterType((*GreeterResponse)(nil), "GreeterResponse")
	proto.RegisterEnum("GreeterRequest_Language", GreeterRequest_Language_name, GreeterRequest_Language_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GreeterService service

type GreeterServiceClient interface {
	Greet(ctx context.Context, in *GreeterRequest, opts ...grpc.CallOption) (*GreeterResponse, error)
}

type greeterServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreeterServiceClient(cc *grpc.ClientConn) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) Greet(ctx context.Context, in *GreeterRequest, opts ...grpc.CallOption) (*GreeterResponse, error) {
	out := new(GreeterResponse)
	err := grpc.Invoke(ctx, "/GreeterService/Greet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreeterService service

type GreeterServiceServer interface {
	Greet(context.Context, *GreeterRequest) (*GreeterResponse, error)
}

func RegisterGreeterServiceServer(s *grpc.Server, srv GreeterServiceServer) {
	s.RegisterService(&_GreeterService_serviceDesc, srv)
}

func _GreeterService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreeterService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Greet(ctx, req.(*GreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreeterService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x2a, 0xe0, 0xe2, 0x73, 0x87, 0x08,
	0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xe9, 0x70, 0xb1, 0xe4, 0x24, 0xe6, 0xa5, 0x4b,
	0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x49, 0xe8, 0xa1, 0x4a, 0xeb, 0xf9, 0x24, 0xe6, 0xa5, 0x97,
	0x26, 0xa6, 0xa7, 0x06, 0x81, 0x55, 0x29, 0x19, 0x70, 0x71, 0xc0, 0x44, 0x84, 0xb8, 0xb9, 0xd8,
	0x5d, 0xf3, 0xd2, 0x73, 0x32, 0x8b, 0x33, 0x04, 0x18, 0x40, 0x9c, 0xe0, 0x82, 0xc4, 0x3c, 0x10,
	0x87, 0x51, 0x88, 0x8b, 0x8b, 0xcd, 0xad, 0x28, 0x35, 0x2f, 0x39, 0x43, 0x80, 0x49, 0x49, 0x9d,
	0x8b, 0x1f, 0x6e, 0x64, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x08, 0x17, 0x2b, 0xd8, 0x55,
	0x60, 0x3b, 0x39, 0x83, 0x20, 0x1c, 0x23, 0x3b, 0xb8, 0xd3, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0x85, 0x74, 0xb8, 0x58, 0xc1, 0x22, 0x42, 0xfc, 0x68, 0xae, 0x92, 0x12, 0xd0, 0x43, 0x33,
	0x53, 0x89, 0xc1, 0x89, 0x25, 0x8a, 0xa9, 0x20, 0x29, 0x89, 0x0d, 0xec, 0x4f, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0xe7, 0xb5, 0xd1, 0xf8, 0x00, 0x00, 0x00,
}
