apiVersion: v1
kind: Service
metadata: 
  name: name.grpcsvr.io
spec: 
  selector: 
    app: name-pod
  ports:
    - port: 8090
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: name-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: name-pod
    spec:
      containers:
      - name: name
        image: robertojrojas/name-java:1.0.0
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata: 
  name: greeter.grpcsvr.io
spec: 
  selector: 
    app: greeter-pod
  ports:
    - port: 8091
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeter-pod
    spec:
      containers:
      - name: name
        image: robertojrojas/greeter-go:1.0.0
        ports:
        - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata: 
  name: webapp.grpcsvr.io
spec: 
  selector: 
    app: webapp-pod
  ports:
    - name: web
      port: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
      - name: webapp-pod
        image: robertojrojas/webapp-nodejs:1.0.0
        env:
        - name: NAME_SERVICE_HOST
          value: name.grpcsvr.io
        - name: NAME_SERVICE_PORT
          value: "8090"
        - name: GREETER_SERVICE_HOST
          value: greeter.grpcsvr.io
        - name: GREETER_SERVICE_PORT
          value: "8091"
        ports:
        - containerPort: 8080
